### ISSUE TITLE
[Bug]: instant crashes after successful sign-in

### ISSUE THREAD

**Issue by YX42** [streamyfin/streamyfin#313]
### What happened?

App crashes after successfully connecting to Jellyfin server and instantly every time you open the app afterwards.

### Reproduction steps

1. Install Streamyfin
2. Connect to Jellyfin server
3. Enter username and password

### Which device and operating system are you using?

Sony XZ2 Android 10

### Version

0.22.0

**Comment by fredrikburmester** [comment]
Hi could you try to remove the app completely and reinstall it?

**Comment by YX42** [comment]
Somehow it works now without reinstalling
