### ISSUE TITLE
[Bug]: shows with named and numbered seasons don't work

### ISSUE THREAD

**Issue by Simon-Eklundh** [streamyfin/streamyfin#337]
### What happened?

I've got a show that has one season called "Season 1" and one season called "MIA". 
I can't swap off of Season 1.

### Reproduction steps

1. have a season called "Season 1" and one called "TEST"
2. open the show in streamyfin
3. try to swap seasons

### Which device and operating system are you using?

samsung galaxy s22 ultra, android 14

### Version

0.23.0

**Comment by fredrikburmester** [comment]
Fixed in future release
